name: Build (MacOS)

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'cpu_source/*'
      - '.github/workflows/macos.yml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Ninja
      run: pip install ninja

    - name: Download VapourSynth headers
      run: |
        wget -q -O vs.zip https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth*/ vapoursynth
    
    - name: Build
      run: |
        cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D VAPOURSYNTH_INCLUDE_DIRECTORY=vapoursynth
        cmake --build build --config Release
        cmake --install build --prefix artifact
        
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: VapourSynth-BM3DCUDA-MacOS
        path: artifact
